### ISSUE TITLE
CT Property value not valid: value not in validValues: 2.4021885603693818

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-pairs#41]
```
number-pairs : fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349291055%7D&brand=phet&ea&fuzz
ERROR: QUERY: brand=phet&ea&fuzz
Error: Assertion failed: validation failed for value:
 2.4021885603693818
 Property value not valid: value not in validValues: 2.4021885603693818
 prunedValidator:
 {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/assert/js/assert.js:45:13)
    at assert (../../../../../axon/js/validate.ts:32:16)
    at validate (../../../../../axon/js/ReadOnlyProperty.ts:324:14)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:287:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:267:11)
    at set (../../../../../axon/js/Property.ts:65:10)
    at set (../../../../../sun/js/SliderTrack.ts:151:20)
    at event (../../../../../sun/js/SliderTrack.ts:168:26)
    at _start (../../../../../../scenery/js/listeners/DragListener.ts:323:26)
    at callback (../../../../../../scenery/js/listeners/PressListener.ts:736:16)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/listeners/PressListener.ts:487:22)
    at press (../../../../../../scenery/js/listeners/DragListener.ts:294:26)
    at press (../../../../../../scenery/js/listeners/PressListener.ts:777:9)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1875:91)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1914:11)
    at dispatchToTargets (../../../../../../scenery/js/input/Input.ts:1828:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1659:9)
    at downEvent (../../../../../../scenery/js/input/Input.ts:495:11)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1251:26)
    at touchStart (../../../../../../scenery/js/input/InputFuzzer.js:214:24)
    at touchStart (../../../../../../scenery/js/input/InputFuzzer.js:47:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1043:44)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733348568147%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349291055%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733348568147%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349291055%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349291055%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[LOADED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733348568147%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349291055%7D
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/chipper/dist/js/tambo/js/phetAudioContext.js" line: 11}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  validation failed for value: 2.4021885603693818 Property value not valid: value not in validValues: 2.4021885603693818 prunedValidator: {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
[CONSOLE] Debug info: {
  "seed": 0.8155816094449975,
  "currentScreenName": "SumScreen"
}
[CONSOLE] Assertion failed:  validation failed for value: 3 Property value not valid: value not in validValues: 3 prunedValidator: {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
[CONSOLE] Debug info: {
  "seed": 0.8155816094449975,
  "currentScreenName": "SumScreen"
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: validation failed for value:
 2.4021885603693818
 Property value not valid: value not in validValues: 2.4021885603693818
 prunedValidator:
 {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: validation failed for value:
 3
 Property value not valid: value not in validValues: 3
 prunedValidator:
 {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}

id: "Sparky Node Firefox"
Snapshot from 12/4/2024, 2:42:48 PM

----------------------------------

number-pairs : fuzz : unbuilt : listenerOrderRandom
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733348568147%22%2C%22timestamp%22%3A1733349245599%7D&brand=phet&ea&fuzz&listenerOrder=random
ERROR: QUERY: brand=phet&ea&fuzz&listenerOrder=random
Error: Assertion failed: reentry detected, value=9.976744186046512, oldValue=18.545454545454547
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1733348568147/assert/js/assert.js:45:13)
    at assert (../../../../../axon/js/ReadOnlyProperty.ts:339:14)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:287:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:267:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at viewToModelX (../../../../../../../number-pairs/js/common/view/BeadsOnWireNode.ts:292:77)
    at forEach (../../../../../../../number-pairs/js/common/view/BeadsOnWireNode.ts:288:20)
    at handleBeadMove (../../../../../../../number-pairs/js/common/view/BeadsOnWireNode.ts:168:17)
    at onDrag (../../../../../../../number-pairs/js/common/view/BeadNode.ts:67:29)
    at _dragListener (../../../../../../scenery/js/listeners/PressListener.ts:533:9)
    at call (../../../../../../scenery/js/listeners/DragListener.ts:267:35)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/listeners/DragListener.ts:423:21)
    at drag (../../../../../../scenery/js/listeners/PressListener.ts:904:13)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1875:91)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1824:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1732:11)
    at branchChangeEvents (../../../../../../scenery/js/input/Input.ts:1672:9)
    at moveEvent (../../../../../../scenery/js/input/Input.ts:426:11)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1207:25)
    at mouseMove (../../../../../../scenery/js/input/InputFuzzer.js:302:24)
    at mouseMove (../../../../../../scenery/js/input/InputFuzzer.js:43:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1043:44)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
====================
```

**Comment by marlitas** [comment]
This should be resolved above. I'll keep open until I no longer see this particular error on CT.

**Comment by marlitas** [comment]
Seems to be clear from CT. Closing.
