### ISSUE TITLE
CT Cannot read properties of undefined (reading 'minus')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-pairs#52]
```
number-pairs : fuzz : built
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz
ERROR: QUERY: fuzz
Uncaught TypeError: Cannot read properties of undefined (reading 'minus')
STACK: TypeError: Cannot read properties of undefined (reading 'minus')
    at AA.setCenter (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:485375)
    at set center [as center] (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:485412)
    at <unknown> (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:1787467)
    at o.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:29984)
    at o.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:29681)
    at r._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:22076)
    at r.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:21576)
    at r.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:21380)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:15121)
    at <unknown> (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:1743850)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fbuild%2Fphet%2Fnumber-pairs_en_phet.html&simQueryParameters=fuzz&duration=80000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fbuild%2Fphet%2Fnumber-pairs_en_phet.html&simQueryParameters=fuzz&duration=80000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz
[LOADED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fbuild%2Fphet%2Fnumber-pairs_en_phet.html&simQueryParameters=fuzz&duration=80000&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'minus')
    at AA.setCenter (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:485375)
    at set center [as center] (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:485412)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:1787467
    at o.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:29984)
    at o.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:29681)
    at r._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:22076)
    at r.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:21576)
    at r.set (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:21380)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:15121)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1735000732098/number-pairs/build/phet/number-pairs_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735002221898%7D&fuzz:1121:1743850
[CONSOLE] continuous-test-error

id: "Bayes Node Chrome"
Snapshot from 12/23/2024, 5:38:52 PM

----------------------------------

number-pairs : fuzz : unbuilt : listenerOrderRandom
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001414225%7D&brand=phet&ea&fuzz&listenerOrder=random
ERROR: QUERY: brand=phet&ea&fuzz&listenerOrder=random
Error: Assertion failed: reentry detected, value=Vector2(914.5, 455.53265), oldValue=Vector2(327.8333333333333, 432.875)
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/assert/js/assert.js:45:21
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/assert/js/assert.js:45:21)
    at assert (../../../../../axon/js/ReadOnlyProperty.ts:340:14)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at property (../../../../../twixt/js/AnimationTarget.ts:322:6)
    at setValue (../../../../../twixt/js/AnimationTarget.ts:359:9)
    at update (../../../../../twixt/js/Animation.ts:319:24)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:196:13)
    at emit (../../../../../joist/js/Sim.ts:456:16)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../joist/js/Sim.ts:1084:30)
    at stepSimulation (../../../../../joist/js/Sim.ts:1074:11)
    at stepOneFrame (../../../../../joist/js/Sim.ts:1049:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001414225%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001414225%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001414225%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[LOADED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1735000732098%2Fnumber-pairs%2Fnumber-pairs_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-pairs%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001414225%7D
[CONSOLE] listenerOrder random seed: 765494
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/chipper/dist/js/tambo/js/phetAudioContext.js" line: 11}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  reentry detected, value=6, oldValue=7
[CONSOLE] Debug info: {
  "seed": 0.3460327142239048,
  "currentScreenName": "IntroScreen",
  "secondsSinceSimStarted": 15.381
}
[CONSOLE] Assertion failed:  reentry detected, value=Vector2(914.5, 455.53265), oldValue=Vector2(327.8333333333333, 432.875)
[CONSOLE] Debug info: {
  "seed": 0.3460327142239048,
  "currentScreenName": "IntroScreen",
  "secondsSinceSimStarted": 15.424
}
[CONSOLE] Assertion failed:  reentry detected, value=Vector2(914.5, 453), oldValue=Vector2(914.5, 455.53265)
[CONSOLE] Debug info: {
  "seed": 0.3460327142239048,
  "currentScreenName": "HomeScreen",
  "secondsSinceSimStarted": 15.611
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=6, oldValue=7
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=Vector2(914.5, 455.53265), oldValue=Vector2(327.8333333333333, 432.875)
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=Vector2(914.5, 453), oldValue=Vector2(914.5, 455.53265)

id: "Sparky Node Firefox"
Snapshot from 12/23/2024, 5:38:52 PM

----------------------------------

number-pairs : interactive-description-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/number-pairs/number-pairs_en.html?continuousTest=%7B%22test%22%3A%5B%22number-pairs%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1735000732098%22%2C%22timestamp%22%3A1735001658998%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true
ERROR: QUERY: brand=phet&ea&fuzz&supportsInteractiveDescription=true
Error: Assertion failed: validation failed for value:
 1.0307599889408103
 Property value not valid: value not in validValues: 1.0307599889408103
 prunedValidator:
 {
  "valueType": "number",
  "validValues": [
    1
  ],
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/assert/js/assert.js:45:21
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1735000732098/assert/js/assert.js:45:21)
    at assert (../../../../../axon/js/validate.ts:32:16)
    at validate (../../../../../axon/js/ReadOnlyProperty.ts:325:14)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:65:10)
    at set (../../../../../sun/js/SliderTrack.ts:151:20)
    at event (../../../../../sun/js/SliderTrack.ts:168:26)
    at _start (../../../../../../scenery/js/listeners/DragListener.ts:323:26)
    at callback (../../../../../../scenery/js/listeners/PressListener.ts:743:16)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/listeners/PressListener.ts:494:22)
    at press (../../../../../../scenery/js/listeners/DragListener.ts:294:26)
    at press (../../../../../../scenery/js/listeners/DragListener.ts:438:11)
    at tryTouchSnag (../../../../../../scenery/js/listeners/DragListener.ts:687:9)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1866:99)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1914:11)
    at dispatchToTargets (../../../../../../scenery/js/input/Input.ts:1828:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1732:11)
    at branchChangeEvents (../../../../../../scenery/js/input/Input.ts:1672:9)
    at moveEvent (../../../../../../scenery/js/input/Input.ts:532:13)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1280:25)
    at touchMove (../../../../../../scenery/js/input/InputFuzzer.js:229:24)
    at touchMove (../../../../../../scenery/js/input/InputFuzzer.js:51:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1146:42)
    at fuzzFrame (../../../../../joist/js/Sim.ts:1047:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1041:11)
```

**Comment by marlitas** [comment]
I did a bunch of CT error and fuzzing work yesterday and today... I'm not seeing this error come up in my fuzzing or on CT now, but I'll keep it open for a bit longer to confirm it's truly gone.

**Comment by marlitas** [comment]
No longer seeing this error on CT. Closing.
